name: Check
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: Lint-Check
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: install
        run: npm ci
      - name: Lint-Test
        run: npm run test